#!/bin/bash

set -e

echo "Shorty litestream database checks commencing..."
if [ -f /data/shorty.db ];then
  echo "Database already exists, skipping restore"
else
  echo "No Database found, restoring from replica if exists"
  echo "litestream_local_db_path: ${LITESTREAM_LOCAL_DB_PATH}"
  litestream restore -v -if-replica-exists -o /data/shorty.db "${LITESTREAM_LOCAL_DB_PATH}"
fi

printf "Litestream checks completed.\nStarting app...\n"
exec litestream replicate -exec "/usr/local/bin/myapp"
